### ISSUE TITLE
在线demo的用户名密码在哪儿查看？

### ISSUE THREAD

**Issue by almas-x** [YaoApp/demo-crm#4]

**Comment by yahuian** [comment]
@almas1992 从[文档](https://yaoapps.com/doc/a.%E4%BB%8B%E7%BB%8D/a.%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97#%E6%BC%94%E7%A4%BA)页面点击”演示“按钮能直接进去。

**Comment by almas-x** [comment]
我就从文档中点击“演示”跳过去的，可还是会显示登录页面，要求输入用户名和密码

> @almas1992 从[文档](https://yaoapps.com/doc/a.%E4%BB%8B%E7%BB%8D/a.%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97#%E6%BC%94%E7%A4%BA)页面点击”演示“按钮能直接进去。

**Comment by yahuian** [comment]
哪我不太清楚了，用 chrome 直接试试这个 https://demo-crm.yaoapps.com/xiang/login/admin?autoLogin=true 呢？

**Comment by almas-x** [comment]
> 哪我不太清楚了，用 chrome 直接试试这个 https://demo-crm.yaoapps.com/xiang/login/admin?autoLogin=true 呢？

这个可以
